### ISSUE TITLE
Upgrade swagger UI

### ISSUE THREAD

**Issue by Niklv** [BiteBit/koa-oai-router#24]
New v3 available.

**Comment by BiteBit** [comment]
Thanks for issue.
I will read the released notes at first and upgrade to v3 after testing in a few days.

**Comment by BiteBit** [comment]
Sorry for making you wait so long, becasue i'm too busy these days.
I fork swagger-ui 3.0.8 and make it support koa-oai-router options. 
The new swagger still has some features which can not be supported, so i'm still keeping the previous version api explorer.
I have added a **api-explorer-v3** endpoint to swagger-ui 3.0.8.
You can use it like this
```js
  app.use(router.apiExplorer());
  app.use(router.apiExplorerV3());
```
Now, you can open **/api-explorer** from the 2.x, and open **/api-explorer-v3** for the 3.x.
When the new swagger-ui was stable, i will replace it.

**Comment by BiteBit** [comment]
I will update the readme and npm publish 1.1.0 at tonight

**Comment by BiteBit** [comment]
#26

**Comment by BiteBit** [comment]
Finish at version 1.1.1
