### ISSUE TITLE
[Question] 'controllerDir' and 'x-oai-controller' name choice.

### ISSUE THREAD

**Issue by stickyhands** [BiteBit/koa-oai-router#25]
Hi,

First, I wanted to say that your router is really great !

But I have a question about x-oai-controller and controllerDir names.
Why didnt you name them "x-oai-middleware" and "middlewareDir" ?

**Comment by BiteBit** [comment]
Thanks for your advice.
I design it as a MVC framework router, so i name it controller in the very beginning.
While your advice makes me realize that koa middleware is better.
In the next version, I will add alias **middlewareDir** and **x-oai-middleware** . And the old two terms will be observed in terms of compatibility.

**Comment by stickyhands** [comment]
great !
