### ISSUE TITLE
Not getting parameter from path

### ISSUE THREAD

**Issue by amunhoz** [BiteBit/koa-oai-router#31]
It looks like it's not parsing the parameter in path in any way.
Example: in the route /user/{userId}, the userID value is not in request.query or request.param
Could not find anywhere.

**Comment by BiteBit** [comment]
Koa-oai-router depends on [koa-router](https://github.com/alexmingoia/koa-router), you can find detail of [URL parameters](https://github.com/alexmingoia/koa-router/tree/master#url-parameters) at here.
```js
router.get('/:category/:title', function (ctx, next) {
  console.log(ctx.params);
  // => { category: 'programming', title: 'how-to-node' }
});
```
