### ISSUE TITLE
Protected routes

### ISSUE THREAD

**Issue by werepa** [BiteBit/koa-oai-router#37]
How can I protect a specific route using koa-oai-router?

**Comment by BiteBit** [comment]
Sorry, i do't known what's the meaning of ”protect“? 
Disable, invisible or other meanings. Can you offer more detail of protect's behavior?
Thank you!

**Comment by werepa** [comment]
Thanks for listening. I would like to define security routes (JWT, for example). Before I used the following code for this:

app.use(koaJwt({ secret: 'secr3t' }).unless({ path: [/^\/public|] }));  // this is not working together with koa-oai-router.

* For protect all routes that not start with /public

I would like the code to execute a function to check if the user is allowed to access that route.

**Comment by werepa** [comment]
I found my mistake:

app.use(koaJwt({ secret: 'secr3t' }).unless({ path: [/^\/public|^\/docs-v3|^\/koa-oai-router-v3/] }));

This code fix it.

**Comment by BiteBit** [comment]
Ok, that's good.
