### ISSUE TITLE
[Question] wrap every route into a try catch

### ISSUE THREAD

**Issue by stickyhands** [BiteBit/koa-oai-router#38]
Is it possible to add a middleware as the first one of the chain for any route ? (without setting it mannually in the chain in the x-oai-controller section).

My plan is to easily wrap everything into a try catch.

**Comment by BiteBit** [comment]
Wrap a koa middleware and **use** it before **router.routes()**.
You can make it.

Here is the example.
```js
const app = new Koa();
const router = new Router(opt);

app.use((ctx, next) => {
  console.log('app use');
  return next();
});

app.use(router.routes());
app.use(router.apiExplorer());
```

**Comment by stickyhands** [comment]
as you told me this is what I tried : 

```
app.use(async (ctx, next) => {
  try {
    console.log('app use ;)');

    await next();
  } catch (err) {
    console.log('caught in server.js ?');

    winston.error(err);
    ctx.status = err.status || 500;
    ctx.body = err.status;
    ctx.app.emit('error', err, ctx);
  }
});
```

But i never manage to catch errors in there

**Comment by BiteBit** [comment]
I'm sorry, i catch the errors in [response middleware](https://github.com/BiteBit/koa-oai-router/blob/master/lib/validator/responses.js#L18)
You can design your custom error handler by doing this, [errorHandler](https://github.com/BiteBit/koa-oai-router#errorhandler).
