### ISSUE TITLE
support boolean type verification in url query object 

### ISSUE THREAD

**Issue by air-cc** [BiteBit/koa-oai-router#4]
like `/users?detail=true`,  now return:

> error: 'Invalid type: string (expected boolean)'

**Comment by BiteBit** [comment]
At this moment, **koa-oai-router** use [tv4](https://github.com/geraintluff/tv4) as Json Schema validator and **koa** parse the query parameters through **querystring** which will parse value as string.

**Comment by BiteBit** [comment]
I found another Json Schema validator [ajv](https://github.com/epoberezkin/ajv), it has better [performance](https://github.com/ebdrup/json-schema-benchmark) and support [data type coercion](https://github.com/epoberezkin/ajv/blob/master/COERCION.md).
I will add **validator** as option, *ajv* as default engine.

**Comment by air-cc** [comment]
Thanks
