### ISSUE TITLE
[Question] Do you have a roadmap ?

### ISSUE THREAD

**Issue by rlataguerra** [BiteBit/koa-oai-router#47]
* Do you have a roadmap for the future of this project ?
* Do you need any help on any topic related to the project ?

**Comment by BiteBit** [comment]
No, what i want to do is almost done. In my production scene it works well now. I need some inspiration.

To be honest, I don't like this usage now.  it's too difficult to newbie, not easy to use.
I am considering a new project with simpler usage and better project structure. A decorator style web framework. Of course, features of this project will be support elegant.

topics:
* OAI 3.0 is still not support.

**Comment by jsdevel** [comment]
@rlataguerra check out https://github.com/kogosoftwarellc/open-api/tree/master/packages/koa-openapi.  V3 is supported and it employs a modular architecture for fast iteration.
