### ISSUE TITLE
What's wrong with this api path?

### ISSUE THREAD

**Issue by mkgn** [BiteBit/koa-oai-router#50]
Hi,

General setup works fine and i can see the swagger doc with all the details of my api. However when I try to call an API with below swagger format:

  '/user/{id}':
    get:
      x-oai-middleware:
        - file: users
          handler: get
      parameters:
        - name: Authorization
          in: header
          type: string
        - name: id
          in: path
          type: integer

I get a 404. in swagger doc, my base path is set to /api. So in swagger explorer this particular api is listed as(after giving sample data);
curl -X GET "https://localhost:8000/api/user/1" -H  "accept: application/json" -H  "Authorization: sfasdff"

My /controller directory has users.js file with:

import koa from 'koa';
async function get(ctx:koa.Context, next:Function) {
	ctx.response.body = ctx.params.id; //expects to echo the received id via path.
}

App didn't complain about whether it managed to load the controllers etc.. So i think below has worked fine;
	router.mount(new routerMiddleware(), path.resolve(__dirname, 'controllers'));

Any idea why it gets a 404 ?

**Comment by mkgn** [comment]
I got this sorted out. The controller directory path wasn't working. I had to use path.resolve(__dirname, 'controllers') to get it to work.

**Comment by BiteBit** [comment]
You can start with **DEBUG=koa-oai-router.*** to debug app. And you can see the [examples](https://github.com/oaijs/koa-oai-router-examples).
