### ISSUE TITLE
query schema at least has one 'required' item

### ISSUE THREAD

**Issue by air-cc** [BiteBit/koa-oai-router#6]
That's too bad!

**Comment by BiteBit** [comment]
I using Json-Schema to validate parameters, but [Json-Schema](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.15) says:
> required:
>The value of this keyword MUST be an array. This array MUST have at least one element. Elements of this array MUST be strings, and MUST be unique.
>An object instance is valid against this keyword if its property set contains all elements in this keyword's array value.

But [OAI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7) not validate query parameters through Json-Schema. Query could be no parameter. 
So i inject a default required key **koa-oai-router:default:required:just4validatequery** for **query** if it's schema has no required field.
PR #7
